//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingComponent
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftPkg
    {
        public string SoftPkgID { get; set; }
        public int computerID { get; set; }
        public string SoftPkgName { get; set; }
        public string SoftPkgDesc { get; set; }
        public string LicenceType { get; set; }
        public string LicenceKey { get; set; }
    
        public virtual Computer Computer { get; set; }
    }
}
